# Resumo:
# - Contem as regras Spark de Data Quality para NOAA, TLC e Taxi Zone Lookup.
# - Cada validador recebe um DataFrame e devolve validos, invalidos, metricas e status.

from __future__ import annotations

from uuid import uuid4

from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from pyspark.sql import types as T

from v2.pipelines.quality.config import (
    NOAAQualityConfig,
    TLCQualityConfig,
    TaxiZoneLookupQualityConfig,
)
from v2.pipelines.quality.models import (
    DataQualityResult,
    QualityMetrics,
    QualityStatus,
    SchemaValidationResult,
    utc_now,
)

TEMP_DUPLICATE_COUNT_COLUMN = "_dq_duplicate_count"
TEMP_FAILED_RULES_COLUMN = "_dq_failed_rules"

QualityConfig = NOAAQualityConfig | TLCQualityConfig | TaxiZoneLookupQualityConfig


def validate_noaa_data(
    df: DataFrame,
    config: NOAAQualityConfig | None = None,
    pipeline_run_id: str | None = None,
) -> DataQualityResult:
    """Validate normalized NOAA observations before Silver publication.

    Expected input grain: one row per NOAA observation with columns generated by
    `silver_noaa_weather.normalize_results`.
    """

    resolved_config = config or NOAAQualityConfig()
    resolved_run_id = pipeline_run_id or str(uuid4())
    schema_validation = validate_schema(df, resolved_config)

    if has_critical_schema_error(schema_validation, resolved_config):
        return build_structural_failure_result(
            df=df,
            config=resolved_config,
            pipeline_run_id=resolved_run_id,
            schema_validation=schema_validation,
        )

    with_duplicate_markers = add_duplicate_marker(
        df=df,
        key_columns=resolved_config.duplicate_key_columns,
    )
    with_rules = add_noaa_failed_rules(with_duplicate_markers, resolved_config)

    metrics = build_noaa_metrics(
        df=with_rules,
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
        schema_validation=schema_validation,
    )

    invalid_records = add_audit_columns(
        df=with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).drop(
            TEMP_DUPLICATE_COUNT_COLUMN
        ),
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
    )
    valid_records = with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).drop(
        TEMP_DUPLICATE_COUNT_COLUMN,
        TEMP_FAILED_RULES_COLUMN,
    )

    return DataQualityResult(
        valid_records=valid_records,
        invalid_records=invalid_records,
        metrics=metrics,
        status=metrics.pipeline_status,
        pipeline_run_id=resolved_run_id,
        dataset_name=resolved_config.dataset_name,
        schema_validation=schema_validation,
    )


def validate_tlc_data(
    df: DataFrame,
    config: TLCQualityConfig | None = None,
    pipeline_run_id: str | None = None,
) -> DataQualityResult:
    """Validate renamed NYC TLC Yellow Taxi trips before Silver publication.

    Expected input grain: one row per trip with columns generated by
    `silver_nyc_tlc.rename_columns`.
    """

    resolved_config = config or TLCQualityConfig()
    resolved_run_id = pipeline_run_id or str(uuid4())
    schema_validation = validate_schema(df, resolved_config)

    if has_critical_schema_error(schema_validation, resolved_config):
        return build_structural_failure_result(
            df=df,
            config=resolved_config,
            pipeline_run_id=resolved_run_id,
            schema_validation=schema_validation,
        )

    with_duplicate_markers = add_duplicate_marker(
        df=df,
        key_columns=resolved_config.duplicate_key_columns,
    )
    with_rules = add_tlc_failed_rules(with_duplicate_markers, resolved_config)

    metrics = build_tlc_metrics(
        df=with_rules,
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
        schema_validation=schema_validation,
    )

    invalid_records = add_audit_columns(
        df=with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).drop(
            TEMP_DUPLICATE_COUNT_COLUMN
        ),
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
    )
    valid_records = with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).drop(
        TEMP_DUPLICATE_COUNT_COLUMN,
        TEMP_FAILED_RULES_COLUMN,
    )

    return DataQualityResult(
        valid_records=valid_records,
        invalid_records=invalid_records,
        metrics=metrics,
        status=metrics.pipeline_status,
        pipeline_run_id=resolved_run_id,
        dataset_name=resolved_config.dataset_name,
        schema_validation=schema_validation,
    )


def validate_taxi_zone_lookup_data(
    df: DataFrame,
    config: TaxiZoneLookupQualityConfig | None = None,
    pipeline_run_id: str | None = None,
) -> DataQualityResult:
    """Validate NYC TLC Taxi Zone Lookup before Silver publication.

    Expected input grain: one row per taxi zone location_id.
    """

    resolved_config = config or TaxiZoneLookupQualityConfig()
    resolved_run_id = pipeline_run_id or str(uuid4())
    schema_validation = validate_schema(df, resolved_config)

    if has_critical_schema_error(schema_validation, resolved_config):
        return build_structural_failure_result(
            df=df,
            config=resolved_config,
            pipeline_run_id=resolved_run_id,
            schema_validation=schema_validation,
        )

    with_duplicate_markers = add_duplicate_marker(
        df=df,
        key_columns=resolved_config.duplicate_key_columns,
    )
    with_rules = add_taxi_zone_lookup_failed_rules(
        with_duplicate_markers,
        resolved_config,
    )

    metrics = build_taxi_zone_lookup_metrics(
        df=with_rules,
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
        schema_validation=schema_validation,
    )

    invalid_records = add_audit_columns(
        df=with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).drop(
            TEMP_DUPLICATE_COUNT_COLUMN
        ),
        config=resolved_config,
        pipeline_run_id=resolved_run_id,
    )
    valid_records = with_rules.filter(F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).drop(
        TEMP_DUPLICATE_COUNT_COLUMN,
        TEMP_FAILED_RULES_COLUMN,
    )

    return DataQualityResult(
        valid_records=valid_records,
        invalid_records=invalid_records,
        metrics=metrics,
        status=metrics.pipeline_status,
        pipeline_run_id=resolved_run_id,
        dataset_name=resolved_config.dataset_name,
        schema_validation=schema_validation,
    )


def validate_schema(
    df: DataFrame,
    config: QualityConfig,
) -> SchemaValidationResult:
    columns = set(df.columns)
    missing_columns = tuple(
        column_name
        for column_name in config.expected_columns
        if column_name not in columns
    )
    unexpected_columns = tuple(
        column_name
        for column_name in df.columns
        if column_name not in set(config.expected_columns)
    )
    incompatible_types = tuple(
        column_name
        for column_name, expected_type in config.expected_schema.items()
        if column_name in columns
        and not is_compatible_type(df.schema[column_name].dataType, expected_type)
    )

    return SchemaValidationResult(
        missing_columns=missing_columns,
        unexpected_columns=unexpected_columns,
        incompatible_types=incompatible_types,
    )


def validate_noaa_schema(
    df: DataFrame,
    config: NOAAQualityConfig,
) -> SchemaValidationResult:
    return validate_schema(df, config)


def is_compatible_type(data_type: T.DataType, expected_type: str) -> bool:
    expected_types: dict[str, tuple[type[T.DataType], ...]] = {
        "date": (T.DateType,),
        "string": (T.StringType,),
        "integer": (T.ByteType, T.ShortType, T.IntegerType, T.LongType),
        "double": (T.FloatType, T.DoubleType, T.DecimalType),
        "timestamp": (T.TimestampType, T.TimestampNTZType),
    }
    return isinstance(data_type, expected_types[expected_type])


def has_critical_schema_error(
    schema_validation: SchemaValidationResult,
    config: QualityConfig,
) -> bool:
    if schema_validation.missing_columns or schema_validation.incompatible_types:
        return config.fail_on_schema_error

    if schema_validation.unexpected_columns:
        return config.fail_on_unexpected_columns

    return False


def build_structural_failure_result(
    df: DataFrame,
    config: QualityConfig,
    pipeline_run_id: str,
    schema_validation: SchemaValidationResult,
) -> DataQualityResult:
    total_records = df.count()
    invalid_records = total_records
    rule_codes = schema_validation.critical_rule_codes or ("SCHEMA_ERROR",)
    schema_error_count = len(schema_validation.critical_rule_codes)
    quality_percentage = calculate_quality_percentage(0, total_records)
    status = QualityStatus.FAIL

    audited_invalid = add_structural_audit_columns(
        df=df,
        config=config,
        pipeline_run_id=pipeline_run_id,
        rule_codes=rule_codes,
    )

    metrics = QualityMetrics(
        pipeline_run_id=pipeline_run_id,
        dataset_name=config.dataset_name,
        execution_timestamp=utc_now(),
        total_records=total_records,
        valid_records=0,
        invalid_records=invalid_records,
        quality_percentage=quality_percentage,
        duplicate_count=0,
        null_error_count=0,
        schema_error_count=schema_error_count,
        range_error_count=0,
        future_date_count=0,
        pipeline_status=status,
        missing_columns=schema_validation.missing_columns,
        unexpected_columns=schema_validation.unexpected_columns,
        incompatible_types=schema_validation.incompatible_types,
    )

    return DataQualityResult(
        valid_records=df.limit(0),
        invalid_records=audited_invalid,
        metrics=metrics,
        status=status,
        pipeline_run_id=pipeline_run_id,
        dataset_name=config.dataset_name,
        schema_validation=schema_validation,
    )


def add_duplicate_marker(df: DataFrame, key_columns: tuple[str, ...]) -> DataFrame:
    base = df.alias("base")
    duplicate_counts = df.groupBy(*key_columns).agg(
        F.count("*").alias(TEMP_DUPLICATE_COUNT_COLUMN)
    ).alias("duplicates")

    join_condition = [
        F.col(f"base.{column_name}").eqNullSafe(F.col(f"duplicates.{column_name}"))
        for column_name in key_columns
    ]

    return base.join(duplicate_counts, on=join_condition, how="left").select(
        F.col("base.*"),
        F.coalesce(
            F.col(f"duplicates.{TEMP_DUPLICATE_COUNT_COLUMN}"),
            F.lit(1),
        ).alias(TEMP_DUPLICATE_COUNT_COLUMN),
    )


def add_noaa_failed_rules(df: DataFrame, config: NOAAQualityConfig) -> DataFrame:
    failed_rules = F.array(
        F.when(is_empty_record(config.expected_columns), F.lit("EMPTY_RECORD")),
        F.when(
            has_null_required_field(config.required_columns),
            F.lit("NULL_REQUIRED_FIELD"),
        ),
        F.when(F.col("data_clima").isNull(), F.lit("INVALID_DATE")),
        F.when(F.col("data_clima") > F.current_date(), F.lit("FUTURE_DATE")),
        F.when(is_missing_station_id(), F.lit("MISSING_STATION_ID")),
        F.when(
            is_invalid_datatype(config.allowed_datatypes),
            F.lit("INVALID_DATATYPE"),
        ),
        F.when(is_value_out_of_range(config), F.lit("CLIMATE_VALUE_OUT_OF_RANGE")),
        F.when(F.col(TEMP_DUPLICATE_COUNT_COLUMN) > 1, F.lit("DUPLICATE_KEY")),
    )

    return df.withColumn(
        TEMP_FAILED_RULES_COLUMN,
        F.filter(failed_rules, lambda rule_code: rule_code.isNotNull()),
    )


def add_tlc_failed_rules(df: DataFrame, config: TLCQualityConfig) -> DataFrame:
    failed_rules = F.array(
        F.when(is_empty_record(config.expected_columns), F.lit("EMPTY_RECORD")),
        F.when(
            has_null_required_field(config.required_columns),
            F.lit("NULL_REQUIRED_FIELD"),
        ),
        F.when(is_invalid_vendor_id(), F.lit("INVALID_VENDOR_ID")),
        F.when(is_invalid_tlc_location(config), F.lit("INVALID_LOCATION_ID")),
        F.when(is_invalid_trip_time_range(), F.lit("INVALID_TRIP_TIME_RANGE")),
        F.when(is_tlc_future_date(), F.lit("FUTURE_DATE")),
        F.when(is_pickup_out_of_config_range(config), F.lit("PICKUP_OUT_OF_YEAR")),
        F.when(is_tlc_value_out_of_range(config), F.lit("TRIP_VALUE_OUT_OF_RANGE")),
        F.when(F.col(TEMP_DUPLICATE_COUNT_COLUMN) > 1, F.lit("DUPLICATE_KEY")),
    )

    return df.withColumn(
        TEMP_FAILED_RULES_COLUMN,
        F.filter(failed_rules, lambda rule_code: rule_code.isNotNull()),
    )


def add_taxi_zone_lookup_failed_rules(
    df: DataFrame,
    config: TaxiZoneLookupQualityConfig,
) -> DataFrame:
    failed_rules = F.array(
        F.when(is_empty_record(config.expected_columns), F.lit("EMPTY_RECORD")),
        F.when(
            has_null_required_field(config.required_columns),
            F.lit("NULL_REQUIRED_FIELD"),
        ),
        F.when(is_invalid_lookup_location(config), F.lit("INVALID_LOCATION_ID")),
        F.when(F.col(TEMP_DUPLICATE_COUNT_COLUMN) > 1, F.lit("DUPLICATE_KEY")),
    )

    return df.withColumn(
        TEMP_FAILED_RULES_COLUMN,
        F.filter(failed_rules, lambda rule_code: rule_code.isNotNull()),
    )


def is_empty_record(columns: tuple[str, ...]):
    condition = F.lit(True)

    for column_name in columns:
        condition = condition & F.col(column_name).isNull()

    return condition


def has_null_required_field(required_columns: tuple[str, ...]):
    condition = F.lit(False)

    for column_name in required_columns:
        column = F.col(column_name)
        required_text_columns = {
            "id_estacao",
            "tipo_dado",
            "borough",
            "zona",
            "zona_servico",
        }
        if column_name in required_text_columns:
            condition = condition | column.isNull() | (F.trim(column) == "")
        else:
            condition = condition | column.isNull()

    return condition


def is_missing_station_id():
    return F.col("id_estacao").isNull() | (F.trim(F.col("id_estacao")) == "")


def is_invalid_datatype(allowed_datatypes: tuple[str, ...]):
    return F.col("tipo_dado").isNotNull() & ~F.col("tipo_dado").isin(
        list(allowed_datatypes)
    )


def is_value_out_of_range(config: NOAAQualityConfig):
    value = F.col("valor")
    datatype = F.col("tipo_dado")
    limits = config.limits

    return F.coalesce(
        F.when(
            datatype.isin("TMAX", "TMIN"),
            (value < limits.temperature_min_c) | (value > limits.temperature_max_c),
        )
        .when(
            datatype == "PRCP",
            (value < limits.precipitation_min_mm)
            | (value > limits.precipitation_max_mm),
        )
        .when(
            datatype == "SNOW",
            (value < limits.snow_min_mm) | (value > limits.snow_max_mm),
        )
        .when(
            datatype == "SNWD",
            (value < limits.snow_depth_min_mm)
            | (value > limits.snow_depth_max_mm),
        ),
        F.lit(False),
    )


def is_invalid_vendor_id():
    return F.col("id_vendedor").isNotNull() & (F.col("id_vendedor") <= 0)


def is_invalid_tlc_location(config: TLCQualityConfig):
    limits = config.limits
    pickup_location = F.col("id_local_partida")
    dropoff_location = F.col("id_local_chegada")

    return F.coalesce(
        (
            pickup_location.isNotNull()
            & (
                (pickup_location < limits.min_location_id)
                | (pickup_location > limits.max_location_id)
            )
        )
        | (
            dropoff_location.isNotNull()
            & (
                (dropoff_location < limits.min_location_id)
                | (dropoff_location > limits.max_location_id)
            )
        ),
        F.lit(False),
    )


def is_invalid_trip_time_range():
    return (
        F.col("data_hora_partida").isNotNull()
        & F.col("data_hora_chegada").isNotNull()
        & (F.col("data_hora_chegada") < F.col("data_hora_partida"))
    )


def is_tlc_future_date():
    return F.coalesce(
        (
            F.col("data_hora_partida").isNotNull()
            & (F.col("data_hora_partida") > F.current_timestamp())
        )
        | (
            F.col("data_hora_chegada").isNotNull()
            & (F.col("data_hora_chegada") > F.current_timestamp())
        ),
        F.lit(False),
    )


def is_pickup_out_of_config_range(config: TLCQualityConfig):
    condition = F.lit(False)
    pickup_date = F.to_date(F.col("data_hora_partida"))

    if config.pickup_start_date is not None:
        condition = condition | (
            F.col("data_hora_partida").isNotNull()
            & (pickup_date < F.lit(config.pickup_start_date))
        )

    if config.pickup_end_before_date is not None:
        condition = condition | (
            F.col("data_hora_partida").isNotNull()
            & (pickup_date >= F.lit(config.pickup_end_before_date))
        )

    return condition


def is_tlc_value_out_of_range(config: TLCQualityConfig):
    limits = config.limits
    duration_minutes = F.expr(
        "timestampdiff(SECOND, data_hora_partida, data_hora_chegada) / 60.0"
    )

    return F.coalesce(
        (
            F.col("qtd_passageiros").isNotNull()
            & (
                (F.col("qtd_passageiros") < limits.min_passenger_count)
                | (F.col("qtd_passageiros") > limits.max_passenger_count)
            )
        )
        | (
            F.col("distancia_milhas").isNotNull()
            & (
                (F.col("distancia_milhas") < limits.min_distance_miles)
                | (F.col("distancia_milhas") > limits.max_distance_miles)
            )
        )
        | (
            F.col("valor_tarifa").isNotNull()
            & (F.col("valor_tarifa") < limits.min_fare_amount)
        )
        | (
            F.col("valor_total").isNotNull()
            & (
                (F.col("valor_total") < limits.min_total_amount)
                | (F.col("valor_total") > limits.max_total_amount)
            )
        )
        | (
            F.col("data_hora_partida").isNotNull()
            & F.col("data_hora_chegada").isNotNull()
            & (duration_minutes > limits.max_duration_minutes)
        ),
        F.lit(False),
    )


def is_invalid_lookup_location(config: TaxiZoneLookupQualityConfig):
    limits = config.limits
    location_id = F.col("location_id")

    return F.coalesce(
        location_id.isNotNull()
        & (
            (location_id < limits.min_location_id)
            | (location_id > limits.max_location_id)
        ),
        F.lit(False),
    )


def build_noaa_metrics(
    df: DataFrame,
    config: NOAAQualityConfig,
    pipeline_run_id: str,
    schema_validation: SchemaValidationResult,
) -> QualityMetrics:
    aggregated = df.agg(
        F.count("*").alias("total_records"),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).cast("long")).alias(
            "valid_records"
        ),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).cast("long")).alias(
            "invalid_records"
        ),
        F.sum(rule_hit("DUPLICATE_KEY").cast("long")).alias("duplicate_count"),
        F.sum(rule_hit("NULL_REQUIRED_FIELD").cast("long")).alias("null_error_count"),
        F.sum(rule_hit("CLIMATE_VALUE_OUT_OF_RANGE").cast("long")).alias(
            "range_error_count"
        ),
        F.sum(rule_hit("FUTURE_DATE").cast("long")).alias("future_date_count"),
        F.sum(critical_rule_hit(config).cast("long")).alias("critical_rule_count"),
    ).collect()[0]

    total_records = aggregated["total_records"] or 0
    valid_records = aggregated["valid_records"] or 0
    invalid_records = aggregated["invalid_records"] or 0
    quality_percentage = calculate_quality_percentage(valid_records, total_records)
    status = determine_status(
        quality_percentage=quality_percentage,
        schema_validation=schema_validation,
        config=config,
        has_critical_rule=(aggregated["critical_rule_count"] or 0) > 0,
        total_records=total_records,
    )

    return QualityMetrics(
        pipeline_run_id=pipeline_run_id,
        dataset_name=config.dataset_name,
        execution_timestamp=utc_now(),
        total_records=total_records,
        valid_records=valid_records,
        invalid_records=invalid_records,
        quality_percentage=quality_percentage,
        duplicate_count=aggregated["duplicate_count"] or 0,
        null_error_count=aggregated["null_error_count"] or 0,
        schema_error_count=len(schema_validation.critical_rule_codes),
        range_error_count=aggregated["range_error_count"] or 0,
        future_date_count=aggregated["future_date_count"] or 0,
        pipeline_status=status,
        missing_columns=schema_validation.missing_columns,
        unexpected_columns=schema_validation.unexpected_columns,
        incompatible_types=schema_validation.incompatible_types,
    )


def build_tlc_metrics(
    df: DataFrame,
    config: TLCQualityConfig,
    pipeline_run_id: str,
    schema_validation: SchemaValidationResult,
) -> QualityMetrics:
    aggregated = df.agg(
        F.count("*").alias("total_records"),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).cast("long")).alias(
            "valid_records"
        ),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).cast("long")).alias(
            "invalid_records"
        ),
        F.sum(rule_hit("DUPLICATE_KEY").cast("long")).alias("duplicate_count"),
        F.sum(rule_hit("NULL_REQUIRED_FIELD").cast("long")).alias("null_error_count"),
        F.sum(tlc_range_rule_hit().cast("long")).alias("range_error_count"),
        F.sum(rule_hit("FUTURE_DATE").cast("long")).alias("future_date_count"),
        F.sum(critical_rule_hit(config).cast("long")).alias("critical_rule_count"),
    ).collect()[0]

    total_records = aggregated["total_records"] or 0
    valid_records = aggregated["valid_records"] or 0
    invalid_records = aggregated["invalid_records"] or 0
    quality_percentage = calculate_quality_percentage(valid_records, total_records)
    status = determine_status(
        quality_percentage=quality_percentage,
        schema_validation=schema_validation,
        config=config,
        has_critical_rule=(aggregated["critical_rule_count"] or 0) > 0,
        total_records=total_records,
    )

    return QualityMetrics(
        pipeline_run_id=pipeline_run_id,
        dataset_name=config.dataset_name,
        execution_timestamp=utc_now(),
        total_records=total_records,
        valid_records=valid_records,
        invalid_records=invalid_records,
        quality_percentage=quality_percentage,
        duplicate_count=aggregated["duplicate_count"] or 0,
        null_error_count=aggregated["null_error_count"] or 0,
        schema_error_count=len(schema_validation.critical_rule_codes),
        range_error_count=aggregated["range_error_count"] or 0,
        future_date_count=aggregated["future_date_count"] or 0,
        pipeline_status=status,
        missing_columns=schema_validation.missing_columns,
        unexpected_columns=schema_validation.unexpected_columns,
        incompatible_types=schema_validation.incompatible_types,
    )


def build_taxi_zone_lookup_metrics(
    df: DataFrame,
    config: TaxiZoneLookupQualityConfig,
    pipeline_run_id: str,
    schema_validation: SchemaValidationResult,
) -> QualityMetrics:
    aggregated = df.agg(
        F.count("*").alias("total_records"),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) == 0).cast("long")).alias(
            "valid_records"
        ),
        F.sum((F.size(F.col(TEMP_FAILED_RULES_COLUMN)) > 0).cast("long")).alias(
            "invalid_records"
        ),
        F.sum(rule_hit("DUPLICATE_KEY").cast("long")).alias("duplicate_count"),
        F.sum(rule_hit("NULL_REQUIRED_FIELD").cast("long")).alias("null_error_count"),
        F.sum(rule_hit("INVALID_LOCATION_ID").cast("long")).alias("range_error_count"),
        F.sum(F.lit(0).cast("long")).alias("future_date_count"),
        F.sum(critical_rule_hit(config).cast("long")).alias("critical_rule_count"),
    ).collect()[0]

    total_records = aggregated["total_records"] or 0
    valid_records = aggregated["valid_records"] or 0
    invalid_records = aggregated["invalid_records"] or 0
    quality_percentage = calculate_quality_percentage(valid_records, total_records)
    status = determine_status(
        quality_percentage=quality_percentage,
        schema_validation=schema_validation,
        config=config,
        has_critical_rule=(aggregated["critical_rule_count"] or 0) > 0,
        total_records=total_records,
    )

    return QualityMetrics(
        pipeline_run_id=pipeline_run_id,
        dataset_name=config.dataset_name,
        execution_timestamp=utc_now(),
        total_records=total_records,
        valid_records=valid_records,
        invalid_records=invalid_records,
        quality_percentage=quality_percentage,
        duplicate_count=aggregated["duplicate_count"] or 0,
        null_error_count=aggregated["null_error_count"] or 0,
        schema_error_count=len(schema_validation.critical_rule_codes),
        range_error_count=aggregated["range_error_count"] or 0,
        future_date_count=aggregated["future_date_count"] or 0,
        pipeline_status=status,
        missing_columns=schema_validation.missing_columns,
        unexpected_columns=schema_validation.unexpected_columns,
        incompatible_types=schema_validation.incompatible_types,
    )


def rule_hit(rule_code: str):
    return F.array_contains(F.col(TEMP_FAILED_RULES_COLUMN), rule_code)


def tlc_range_rule_hit():
    return any_rule_hit(
        (
            "INVALID_VENDOR_ID",
            "INVALID_LOCATION_ID",
            "INVALID_TRIP_TIME_RANGE",
            "PICKUP_OUT_OF_YEAR",
            "TRIP_VALUE_OUT_OF_RANGE",
        )
    )


def any_rule_hit(rule_codes: tuple[str, ...]):
    condition = F.lit(False)

    for rule_code in rule_codes:
        condition = condition | rule_hit(rule_code)

    return condition


def critical_rule_hit(config: QualityConfig):
    if not config.critical_rule_codes:
        return F.lit(False)

    condition = F.lit(False)
    for rule_code in config.critical_rule_codes:
        condition = condition | rule_hit(rule_code)

    return condition


def determine_status(
    quality_percentage: float,
    schema_validation: SchemaValidationResult,
    config: QualityConfig,
    has_critical_rule: bool,
    total_records: int,
) -> QualityStatus:
    if config.fail_on_empty and total_records == 0:
        return QualityStatus.FAIL

    if has_critical_schema_error(schema_validation, config) or has_critical_rule:
        return QualityStatus.FAIL

    if schema_validation.has_errors:
        return QualityStatus.WARNING

    if quality_percentage >= config.thresholds.pass_min_percentage:
        return QualityStatus.PASS

    if quality_percentage >= config.thresholds.warning_min_percentage:
        return QualityStatus.WARNING

    return QualityStatus.FAIL


def calculate_quality_percentage(valid_records: int, total_records: int) -> float:
    if total_records == 0:
        return 0.0

    return round(valid_records / total_records * 100, 2)


def add_audit_columns(
    df: DataFrame,
    config: QualityConfig,
    pipeline_run_id: str,
) -> DataFrame:
    return (
        df.withColumn("dq_failed_rules", F.col(TEMP_FAILED_RULES_COLUMN))
        .withColumn("dq_error_code", F.element_at(F.col("dq_failed_rules"), 1))
        .withColumn("dq_error_message", F.array_join(F.col("dq_failed_rules"), "; "))
        .withColumn("dq_validation_timestamp", F.current_timestamp())
        .withColumn("dq_pipeline_run_id", F.lit(pipeline_run_id))
        .withColumn("dq_dataset_name", F.lit(config.dataset_name))
        .drop(TEMP_FAILED_RULES_COLUMN)
    )


def add_structural_audit_columns(
    df: DataFrame,
    config: QualityConfig,
    pipeline_run_id: str,
    rule_codes: tuple[str, ...],
) -> DataFrame:
    rules_array = F.array(*[F.lit(rule_code) for rule_code in rule_codes])
    return (
        df.withColumn("dq_failed_rules", rules_array)
        .withColumn("dq_error_code", F.element_at(F.col("dq_failed_rules"), 1))
        .withColumn("dq_error_message", F.array_join(F.col("dq_failed_rules"), "; "))
        .withColumn("dq_validation_timestamp", F.current_timestamp())
        .withColumn("dq_pipeline_run_id", F.lit(pipeline_run_id))
        .withColumn("dq_dataset_name", F.lit(config.dataset_name))
    )
